
# Oh My Zsh installation
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Set the theme
ZSH_THEME="agnoster"

# Set the plugins
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

# Source Oh My Zsh
source $HOME/.oh-my-zsh/oh-my-zsh.sh

# The welcome message
clear
echo "Welcome to the Bambana Tech Automations Environment"
echo ""

# PS1
PS1='\n\e[1;32mBTA \w\e[0m \$ '

# Install essential packages

# List of packages to install
packages="mpv yt-dlp ranger fzf ripgrep rclone neovim gh tmux htop tldr"

# Check for and install packages
for package in $packages; do
  if ! command -v $package &> /dev/null; then
    echo "Installing $package..."
    pkg install -y $package
  fi
done

# Aliases
alias ls='ls -F'
alias ll='ls -l'
alias la='ls -a'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias mkdir='mkdir -p'
alias h='history'
alias j='jobs -l'
alias c='clear'
alias e='exit'
alias vi='nvim'
alias vim='nvim'

